version: "3.8"
services:
  backend:
    image: "ala842711/spring-react-fullstack:18.3.2022.17.53.38"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev